name: Deployment
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Source Code
        uses: actions/checkout@v3
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Create Version Label
        run: |
          echo "VERSION_LABEL=$(date +'%Y-%m-%d:%H:%M:%S')" >> $GITHUB_ENV
      # Deploy zipped archive to AWS
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_APPLICATION_ENVIRONMENT }}
          version_label: ${{ env.VERSION_LABEL }}
          region: us-east-1
          deployment_package: deploy.zip